/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
var View=Laya.View;
var Dialog=Laya.Dialog;
var Scene=Laya.Scene;
var REG = Laya.ClassUtils.regClass;
export class saceToNormalUI extends Laya.EffectAnimation {
	constructor(){ 
		super();
		    this.ani1=null;
		this.effectData =saceToNormalUI.uiView;;
	}
}
saceToNormalUI.uiView={"type":"View","props":{},"compId":2,"child":[{"type":"Sprite","props":{"y":0,"x":0,"texture":"comp/x.png"},"compId":3}],"animations":[{"nodes":[{"target":3,"keyframes":{"scaleY":[{"value":0.8,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleY","index":0},{"value":1,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleY","index":5}],"scaleX":[{"value":0.8,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleX","index":0},{"value":1,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleX","index":5}]}}],"name":"ani1","id":1,"frameRate":24,"action":0}],"loadList":["comp/x.png"],"loadList3D":[]};
REG("ui.ani.saceToNormalUI",saceToNormalUI);
export class scaleUI extends Laya.EffectAnimation {
	constructor(){ 
		super();
		    this.ani1=null;
		this.effectData =scaleUI.uiView;;
	}
}
scaleUI.uiView={"type":"View","props":{},"compId":2,"child":[{"type":"Button","props":{"y":0,"x":0,"skin":"comp/button.png","label":"label","labelSize":28,"labelFont":"SimHei","labelColors":"#fff,#fff,#e7ce4e","sizeGrid":"14,16,15,19","width":160,"labelPadding":"0,0,1,0"},"compId":3}],"animations":[{"nodes":[{"target":3,"keyframes":{"scaleY":[{"value":1,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleY","index":0},{"value":1.2,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleY","index":12},{"value":1,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleY","index":24}],"scaleX":[{"value":1,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleX","index":0},{"value":1.2,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleX","index":12},{"value":1,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleX","index":24}]}}],"name":"ani1","id":1,"frameRate":60,"action":0}],"loadList":["comp/button.png"],"loadList3D":[]};
REG("ui.ani.scaleUI",scaleUI);
export class scaleToBigUI extends Laya.EffectAnimation {
	constructor(){ 
		super();
		    this.ani1=null;
		this.effectData =scaleToBigUI.uiView;;
	}
}
scaleToBigUI.uiView={"type":"View","props":{},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"skin":"comp/img_blank.png"},"compId":3}],"animations":[{"nodes":[{"target":3,"keyframes":{"scaleY":[{"value":1,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleY","index":0},{"value":1.2,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleY","index":6}],"scaleX":[{"value":1,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleX","index":0},{"value":1.2,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleX","index":6}]}}],"name":"ani1","id":1,"frameRate":24,"action":0}],"loadList":["comp/img_blank.png"],"loadList3D":[]};
REG("ui.ani.scaleToBigUI",scaleToBigUI);
export class scaleToSmallUI extends Laya.EffectAnimation {
	constructor(){ 
		super();
		    this.ani1=null;
		this.effectData =scaleToSmallUI.uiView;;
	}
}
scaleToSmallUI.uiView={"type":"View","props":{},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"skin":"comp/img_hd.png"},"compId":4}],"animations":[{"nodes":[{"target":4,"keyframes":{"scaleY":[{"value":1,"tweenMethod":"linearNone","tween":true,"target":4,"key":"scaleY","index":0},{"value":0.8,"tweenMethod":"linearNone","tween":true,"target":4,"key":"scaleY","index":6}],"scaleX":[{"value":1,"tweenMethod":"linearNone","tween":true,"target":4,"key":"scaleX","index":0},{"value":0.8,"tweenMethod":"linearNone","tween":true,"target":4,"key":"scaleX","index":6}]}}],"name":"ani1","id":1,"frameRate":24,"action":0}],"loadList":["comp/img_hd.png"],"loadList3D":[]};
REG("ui.ani.scaleToSmallUI",scaleToSmallUI);
export class LoadingUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("Loading");
	}
}
REG("ui.LoadingUI",LoadingUI);
export class PhysicsGameMainUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("physicsDemo/PhysicsGameMain");
	}
}
REG("ui.physicsDemo.PhysicsGameMainUI",PhysicsGameMainUI);
export class AniEffectUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/animation/AniEffect");
	}
}
REG("ui.uiDemo.animation.AniEffectUI",AniEffectUI);
export class AtlasAniUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/animation/AtlasAni");
	}
}
REG("ui.uiDemo.animation.AtlasAniUI",AtlasAniUI);
export class FrameAniUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/animation/FrameAni");
	}
}
REG("ui.uiDemo.animation.FrameAniUI",FrameAniUI);
export class TimelineAniUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/animation/TimelineAni");
	}
}
REG("ui.uiDemo.animation.TimelineAniUI",TimelineAniUI);
export class TweenAniUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/animation/TweenAni");
	}
}
REG("ui.uiDemo.animation.TweenAniUI",TweenAniUI);
export class DialogUI extends Dialog {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/Dialog");
	}
}
REG("ui.uiDemo.DialogUI",DialogUI);
export class JoystickUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/interactive/Joystick");
	}
}
REG("ui.uiDemo.interactive.JoystickUI",JoystickUI);
export class ShapeDetectionUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/interactive/ShapeDetection");
	}
}
REG("ui.uiDemo.interactive.ShapeDetectionUI",ShapeDetectionUI);
export class BagListUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/list/BagList");
	}
}
REG("ui.uiDemo.list.BagListUI",BagListUI);
export class ComboBoxUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/list/ComboBox");
	}
}
REG("ui.uiDemo.list.ComboBoxUI",ComboBoxUI);
export class LoopListUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/list/LoopList");
	}
}
REG("ui.uiDemo.list.LoopListUI",LoopListUI);
export class MailListUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/list/MailList");
	}
}
REG("ui.uiDemo.list.MailListUI",MailListUI);
export class RefreshUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/list/Refresh");
	}
}
REG("ui.uiDemo.list.RefreshUI",RefreshUI);
export class TreeListUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/list/TreeList");
	}
}
REG("ui.uiDemo.list.TreeListUI",TreeListUI);
export class MsgUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/Msg");
	}
}
REG("ui.uiDemo.MsgUI",MsgUI);
export class IframeElementUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/page/IframeElement");
	}
}
REG("ui.uiDemo.page.IframeElementUI",IframeElementUI);
export class OpenMainSceneUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/page/OpenMainScene");
	}
}
REG("ui.uiDemo.page.OpenMainSceneUI",OpenMainSceneUI);
export class OpenSceneUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/page/OpenScene");
	}
}
REG("ui.uiDemo.page.OpenSceneUI",OpenSceneUI);
export class UsePanelUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/page/UsePanel");
	}
}
REG("ui.uiDemo.page.UsePanelUI",UsePanelUI);
export class UiMainUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/UiMain");
	}
}
REG("ui.uiDemo.UiMainUI",UiMainUI);
export class ChangeTextureUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/useUI/ChangeTexture");
	}
}
REG("ui.uiDemo.useUI.ChangeTextureUI",ChangeTextureUI);
export class MaskUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/useUI/Mask");
	}
}
REG("ui.uiDemo.useUI.MaskUI",MaskUI);
export class MouseThroughUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/useUI/MouseThrough");
	}
}
REG("ui.uiDemo.useUI.MouseThroughUI",MouseThroughUI);
export class PhysicalCollisionUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/useUI/PhysicalCollision");
	}
}
REG("ui.uiDemo.useUI.PhysicalCollisionUI",PhysicalCollisionUI);
export class ProgressUI extends Scene {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/useUI/Progress");
	}
}
REG("ui.uiDemo.useUI.ProgressUI",ProgressUI);
export class TextShowUI extends Scene {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("uiDemo/useUI/TextShow");
	}
}
REG("ui.uiDemo.useUI.TextShowUI",TextShowUI);