/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import CloseBtn from "./prefab/CloseBtn"
import D3Main from "./scence/d3Demo/D3Main"
import Index from "./Index"
import LoadingRT from "./LoadingRT"
import PhysicsGameMainRT from "./scence/physicsDemo/PhysicsGameMainRT"
import PhysicsGameMain from "./scence/physicsDemo/PhysicsGameMain"
import AtlasAniRT from "./scence/uiDemo/animation/AtlasAniRT"
import FrameAniRT from "./scence/uiDemo/animation/FrameAniRT"
import SkeletonAni from "./scence/uiDemo/animation/SkeletonAni"
import Role from "./prefab/Role"
import Folded from "./script/tween/Folded"
import DialogRT from "./scence/uiDemo/DialogRT"
import Joystick from "./script/mouse/Joystick"
import ShapeDetectionRT from "./scence/uiDemo/interactive/ShapeDetectionRT"
import DragAndTips from "./script/mouse/DragAndTips"
import ShapeDetection from "./scence/uiDemo/interactive/ShapeDetection"
import BagListRT from "./scence/uiDemo/list/BagListRT"
import ComboBoxRT from "./scence/uiDemo/list/ComboBoxRT"
import LoopListRT from "./scence/uiDemo/list/LoopListRT"
import MailListRT from "./scence/uiDemo/list/MailListRT"
import RefreshRT from "./scence/uiDemo/list/RefreshRT"
import ItemBox from "./runtime/box/dataSource/ItemBox"
import TreeListRT from "./scence/uiDemo/list/TreeListRT"
import MsgRT from "./scence/uiDemo/MsgRT"
import IframeElementRT from "./scence/uiDemo/page/IframeElementRT"
import OpenMainScene from "./scence/uiDemo/page/OpenMainScene"
import OpenScene from "./scence/uiDemo/page/OpenScene"
import UsePanelRT from "./scence/uiDemo/page/UsePanelRT"
import BgImg from "./script/mouse/BgImg"
import UiMainRT from "./scence/uiDemo/UiMainRT"
import ProgressRT from "./scence/uiDemo/useUI/ProgressRT"
import TextShowRT from "./scence/uiDemo/useUI/TextShowRT"
import ChangeTextureRT from "./scence/uiDemo/useUI/ChangeTextureRT"
import MouseThroughRT from "./scence/uiDemo/useUI/MouseThroughRT"
import PhysicalCollisionRT from "./scence/uiDemo/useUI/PhysicalCollisionRT"
import MaskRT from "./scence/uiDemo/useUI/MaskRT"
import Bullet from "./prefab/Bullet"
import DropBox from "./prefab/DropBox"
import LoopImg from "./prefab/LoopImg"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("prefab/CloseBtn.js",CloseBtn);
		reg("scence/d3Demo/D3Main.js",D3Main);
		reg("Index.js",Index);
		reg("LoadingRT.js",LoadingRT);
		reg("scence/physicsDemo/PhysicsGameMainRT.js",PhysicsGameMainRT);
		reg("scence/physicsDemo/PhysicsGameMain.js",PhysicsGameMain);
		reg("scence/uiDemo/animation/AtlasAniRT.js",AtlasAniRT);
		reg("scence/uiDemo/animation/FrameAniRT.js",FrameAniRT);
		reg("scence/uiDemo/animation/SkeletonAni.js",SkeletonAni);
		reg("prefab/Role.js",Role);
		reg("script/tween/Folded.js",Folded);
		reg("scence/uiDemo/DialogRT.js",DialogRT);
		reg("script/mouse/Joystick.js",Joystick);
		reg("scence/uiDemo/interactive/ShapeDetectionRT.js",ShapeDetectionRT);
		reg("script/mouse/DragAndTips.js",DragAndTips);
		reg("scence/uiDemo/interactive/ShapeDetection.js",ShapeDetection);
		reg("scence/uiDemo/list/BagListRT.js",BagListRT);
		reg("scence/uiDemo/list/ComboBoxRT.js",ComboBoxRT);
		reg("scence/uiDemo/list/LoopListRT.js",LoopListRT);
		reg("scence/uiDemo/list/MailListRT.js",MailListRT);
		reg("scence/uiDemo/list/RefreshRT.js",RefreshRT);
		reg("runtime/box/dataSource/ItemBox.js",ItemBox);
		reg("scence/uiDemo/list/TreeListRT.js",TreeListRT);
		reg("scence/uiDemo/MsgRT.js",MsgRT);
		reg("scence/uiDemo/page/IframeElementRT.js",IframeElementRT);
		reg("scence/uiDemo/page/OpenMainScene.js",OpenMainScene);
		reg("scence/uiDemo/page/OpenScene.js",OpenScene);
		reg("scence/uiDemo/page/UsePanelRT.js",UsePanelRT);
		reg("script/mouse/BgImg.js",BgImg);
		reg("scence/uiDemo/UiMainRT.js",UiMainRT);
		reg("scence/uiDemo/useUI/ProgressRT.js",ProgressRT);
		reg("scence/uiDemo/useUI/TextShowRT.js",TextShowRT);
		reg("scence/uiDemo/useUI/ChangeTextureRT.js",ChangeTextureRT);
		reg("scence/uiDemo/useUI/MouseThroughRT.js",MouseThroughRT);
		reg("scence/uiDemo/useUI/PhysicalCollisionRT.js",PhysicalCollisionRT);
		reg("scence/uiDemo/useUI/MaskRT.js",MaskRT);
		reg("prefab/Bullet.js",Bullet);
		reg("prefab/DropBox.js",DropBox);
		reg("prefab/LoopImg.js",LoopImg);
    }
}
GameConfig.width = 1334;
GameConfig.height = 750;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "Loading.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = true;
GameConfig.exportSceneToJson = true;

GameConfig.init();
